# Generated by Django 4.0.5 on 2022-09-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
