# Generated by Django 4.0.5 on 2022-09-24 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_alter_photo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_album', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
