# Generated by Django 4.0.5 on 2022-09-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_album_favorites_photo_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='favorites',
        ),
    ]
